POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q0QGV4ZW1wbGUuY29tIiwiZXhwIjoxNzMwMTMwNzkwLCJ1c2VySWQiOjR9.bChjL5qlKmnk5rk-kYe8h49gyYNTSEoqPgLu0VRS4Rc

{
  "name": "Test Event",
  "description": "This is a test event!!!",
  "location": "Test Location",
  "dateTime": "2025-01-01T00:00:00.000Z"
}
