DELETE http://localhost:8080/events/4
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4ZW1wbGUuY29tIiwiZXhwIjoxNzMwMTI5MTk4LCJ1c2VySWQiOjJ9.I7io2WVNppNa9u7neLIbOvtnc7UECedzBzFPwQTfBt4