DELETE http://localhost:8080/events/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4ZW1wbGUuY29tIiwiZXhwIjoxNzMwMTI5NjM2LCJ1c2VySWQiOjJ9.u08CjLocTEoz5Vdl3BCp2Fd7TikVwoJ3-hS0cK1RPAw